import Link from 'next/link'
import Image from 'next/image'
import { ArrowRight, Building2, Check, GraduationCap, HeartPulse, ShieldCheck, Stethoscope } from 'lucide-react'
import type { PublicBlock } from '@/lib/public-content'

export function PublicPageBlocks({blocks}:{blocks:PublicBlock[]}){return <>{blocks.map((block,index)=>{
  if(block.blockType==='hero')return <section className="public-hero-v2" key={index}><div className="container hero-v2-grid"><div className="hero-v2-copy"><span className="eyebrow"><ShieldCheck size={14}/>{block.eyebrow||'MEDICAL CORP'}</span><h1>{block.heading}</h1><p>{block.body}</p><div className="hero-actions"><Link className="btn btn-primary" href={block.primaryHref||'/cursos'}>{block.primaryLabel||'Explorar programas'} <ArrowRight size={16}/></Link><Link className="btn btn-outline" href="/login">Acceso al campus</Link></div><div className="hero-trust-row"><span><Check size={15}/> Contenido especializado</span><span><Check size={15}/> Modalidad flexible</span><span><Check size={15}/> Acompañamiento docente</span></div></div><div className="hero-v2-art"><div className="hero-art-card hero-art-main"><HeartPulse size={26}/><span>Educación continua</span><strong>Conocimiento que se convierte en mejores decisiones.</strong></div><div className="hero-art-card hero-art-small"><Stethoscope size={22}/><span>Práctica profesional</span></div><div className="hero-art-orbit"><GraduationCap size={30}/></div></div></div></section>
  if(block.blockType==='companyInfo')return <section className="section company-about" key={index}><div className="container about-grid"><div>{block.showLogo&&<Image src="/brand/medical-corp-logo.png" width={100} height={100} alt="MEDICAL CORP"/>}<span className="eyebrow">MEDICAL CORP</span><h2>{block.heading}</h2></div><div><p>{block.body}</p></div></div></section>
  if(block.blockType==='courseGrid')return <section className="section public-courses-section" key={index}><div className="container"><div className="section-head"><div><span className="eyebrow">Oferta académica</span><h2>{block.heading||'Programas MEDICAL CORP'}</h2><p>{block.intro}</p></div></div><div className="grid-3">{block.courses.map(c=><article className="course-card-v2" key={c.slug}><div className="course-cover-v2 cover-a"><span className="course-index">Programa académico</span></div><div className="course-card-content"><div className="course-kicker">MEDICAL CORP</div><h3>{c.title}</h3><p>{c.summary}</p><div className="course-meta-v2"><span>{c.estimatedHours?`${c.estimatedHours} horas`:'Modalidad flexible'}</span><span>{c.modality==='LIVE'?'En vivo':c.modality==='HYBRID'?'Híbrido':'Asincrónico'}</span></div><Link className="text-link" href={`/cursos/${c.slug}`}>Conocer programa <ArrowRight size={14}/></Link></div></article>)}</div></div></section>
  if(block.blockType==='contentSection')return <section className="section" key={index}><div className="container" style={{maxWidth:block.alignment==='CENTER'?820:1180,textAlign:block.alignment==='CENTER'?'center':'left'}}><span className="eyebrow">Información</span><h2 style={{fontSize:38,color:'var(--navy)',letterSpacing:'-.035em'}}>{block.heading}</h2><p className="muted" style={{fontSize:16,lineHeight:1.75}}>{block.body}</p></div></section>
  if(block.blockType==='cta')return <section className="section band" key={index}><div className="container"><div className="cta-panel"><div><span className="section-label light">MEDICAL CORP</span><h2>{block.heading}</h2><p className="muted">{block.body}</p></div>{block.buttonLabel&&<Link href={block.buttonHref||'/contacto'} className="btn btn-outline">{block.buttonLabel} <ArrowRight size={15}/></Link>}</div></div></section>
  return null
})}</>}
