'use client'
import { useEffect, useMemo, useState } from 'react'
import { BookOpenText, CheckCircle2, Clock3, FileSpreadsheet, FileText, FileType2, Link2, MessageSquareText, NotebookPen, PlayCircle, Presentation, Send, UploadCloud } from 'lucide-react'
import type { Course, CourseResource } from '@/lib/demo-data'

const iconFor=(type:CourseResource['type'])=>type==='PDF'?FileText:type==='DOCX'?FileType2:type==='XLSX'?FileSpreadsheet:type==='PPTX'?Presentation:Link2

function ClassPanel({course,week}:{course:Course;week:number}){
  const data=course.content[week-1]; const storageKey=`mc_notes_${course.slug}_${week}`; const [notes,setNotes]=useState('')
  useEffect(()=>{setNotes(localStorage.getItem(storageKey)||'')},[storageKey])
  function save(value:string){setNotes(value);localStorage.setItem(storageKey,value)}
  return <div className="workspace-stack"><div className="learning-video"><div className="video-play"><PlayCircle size={42}/></div><div><span className="section-label light">Clase asincrónica</span><h3>{data.classTitle}</h3><p>{data.classDescription}</p><span><Clock3 size={14}/> 38 minutos</span></div></div><div className="panel note-panel"><div className="panel-heading"><div><span className="section-label">Apuntes personales</span><h3><NotebookPen size={18}/> Mis notas de la clase</h3></div><span className="save-indicator">Guardado automático</span></div><textarea className="input note-area" rows={9} value={notes} onChange={e=>save(e.target.value)} placeholder="Escribe aquí tus apuntes, ideas clave, dudas o recordatorios..."/></div></div>
}

function ResourcesPanel({course,week}:{course:Course;week:number}){
  const resources=course.content[week-1].resources
  return <div className="panel"><div className="panel-heading"><div><span className="section-label">Material de apoyo</span><h3>Recursos de la semana</h3></div></div><div className="resource-list">{resources.map(resource=>{const Icon=iconFor(resource.type);return <div className="resource-row" key={resource.title}><div className="resource-icon"><Icon size={22}/></div><div className="resource-copy"><b>{resource.title}</b><p>{resource.description}</p><small>{resource.type}{resource.size?` · ${resource.size}`:''}</small></div><button className="btn btn-outline">Abrir recurso</button></div>})}</div></div>
}

function AssignmentPanel({course,week}:{course:Course;week:number}){
  const assignment=course.content[week-1].assignment
  const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<string|null>(null); const [status,setStatus]=useState(assignment.status)
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview])
  function selectFile(f:File|null){if(preview)URL.revokeObjectURL(preview);setFile(f);setPreview(f?URL.createObjectURL(f):null)}
  function submit(){if(file)setStatus('Enviada')}
  return <div className="workspace-stack"><div className="panel"><div className="assignment-head"><div><span className="section-label">Tarea</span><h3>{assignment.title}</h3><p className="muted">Fecha límite: {assignment.due} · {assignment.points} puntos</p></div><span className={`status ${status==='Calificada'?'success':status==='Enviada'?'blue':'gold'}`}>{status}</span></div><div className="instruction-box"><b>Instrucciones</b><p>{assignment.instructions}</p></div>{assignment.grade&&<div className="grade-callout"><CheckCircle2 size={18}/><div><b>Calificación: {assignment.grade}</b><span>Retroalimentación disponible por el docente.</span></div></div>}</div><div className="panel"><div className="panel-heading"><div><span className="section-label">Entrega</span><h3>Subir tarea</h3></div></div><label className="file-drop file-drop-v2"><UploadCloud size={30}/><b>{file?file.name:'Selecciona o arrastra tu archivo'}</b><span>PDF, Word, Excel o imagen · máximo 25 MB</span><input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg" onChange={e=>selectFile(e.target.files?.[0]||null)}/></label>{file&&<div className="submission-preview"><div className="preview-meta"><div><b>Vista previa de la entrega</b><span>{file.name} · {(file.size/1024/1024).toFixed(2)} MB</span></div><button className="btn btn-outline" onClick={()=>selectFile(null)}>Quitar</button></div>{preview&&file.type.startsWith('image/')&&<img src={preview} alt="Vista previa de la tarea"/>}{preview&&file.type==='application/pdf'&&<iframe src={preview} title="Vista previa PDF"/>}{preview&&!file.type.startsWith('image/')&&file.type!=='application/pdf'&&<div className="generic-file-preview"><FileText size={36}/><span>Archivo preparado para enviar</span></div>}</div>}<textarea className="input" rows={4} placeholder="Comentario opcional para el docente" style={{marginTop:14}}/><button className="btn btn-primary" onClick={submit} disabled={!file} style={{marginTop:14}}><Send size={16}/> Enviar tarea</button>{status==='Enviada'&&<div className="success-note">Entrega enviada correctamente. Estado actual: <b>Enviada</b>.</div>}</div></div>
}

function ForumPanel({course,week}:{course:Course;week:number}){
  const forum=course.content[week-1].forum; const key=`mc_forum_${course.slug}_${week}`; const [text,setText]=useState(''); const [post,setPost]=useState('')
  useEffect(()=>{setPost(localStorage.getItem(key)||'')},[key])
  function publish(){if(text.trim()){localStorage.setItem(key,text.trim());setPost(text.trim());setText('')}}
  return <div className="workspace-stack"><div className="panel"><div className="assignment-head"><div><span className="section-label">Foro de discusión</span><h3>{forum.title}</h3><p className="muted">Cierra: {forum.closes}</p></div><MessageSquareText size={24}/></div><div className="instruction-box"><b>Instrucciones</b><p>{forum.instructions}</p></div>{!post?<><textarea className="input" rows={7} value={text} onChange={e=>setText(e.target.value)} placeholder="Escribe tu participación..."/><button className="btn btn-primary" onClick={publish} style={{marginTop:12}}><Send size={16}/> Publicar participación</button></>:<div className="forum-post own"><div className="forum-avatar">AM</div><div><b>Ana Martínez · Tu participación</b><p>{post}</p><small>Publicado en esta sesión</small></div></div>}</div>{post&&<div className="panel"><div className="panel-heading"><div><span className="section-label">Conversación</span><h3>Participaciones de tus compañeros</h3></div><span className="status blue">{forum.classmates.length} aportes</span></div><div className="forum-history">{forum.classmates.map(entry=><div className="forum-post" key={entry.author}><div className="forum-avatar">{entry.author.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><b>{entry.author}</b><p>{entry.body}</p><small>{entry.date}</small></div></div>)}</div></div>}</div>
}

export function StudentCourseWorkspace({course}:{course:Course}){
  const [week,setWeek]=useState(1); const [tab,setTab]=useState<'class'|'resources'|'assignment'|'forum'>('class')
  const selected=useMemo(()=>course.content[week-1],[course,week])
  return <div className="course-workspace"><aside className="week-rail"><div className="week-rail-head"><span className="section-label">Contenido</span><b>{course.weeks} semanas</b></div>{course.content.map(item=><button key={item.number} onClick={()=>{setWeek(item.number);setTab('class')}} className={week===item.number?'active':''}><span>{String(item.number).padStart(2,'0')}</span><div><b>Semana {item.number}</b><small>{item.title}</small></div></button>)}</aside><section className="workspace-main"><div className="workspace-header"><div><span className="section-label">Semana {week}</span><h2>{selected.title}</h2></div></div><div className="workspace-tabs"><button onClick={()=>setTab('class')} className={tab==='class'?'active':''}><BookOpenText size={16}/> Clase</button><button onClick={()=>setTab('resources')} className={tab==='resources'?'active':''}><FileText size={16}/> Recursos</button><button onClick={()=>setTab('assignment')} className={tab==='assignment'?'active':''}><CheckCircle2 size={16}/> Tarea</button><button onClick={()=>setTab('forum')} className={tab==='forum'?'active':''}><MessageSquareText size={16}/> Foro</button></div>{tab==='class'&&<ClassPanel course={course} week={week}/>} {tab==='resources'&&<ResourcesPanel course={course} week={week}/>} {tab==='assignment'&&<AssignmentPanel course={course} week={week}/>} {tab==='forum'&&<ForumPanel course={course} week={week}/>}</section></div>
}
