/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    companies: Company;
    courses: Course;
    enrollments: Enrollment;
    modules: Module;
    lessons: Lesson;
    resources: Resource;
    assignments: Assignment;
    submissions: Submission;
    forums: Forum;
    'forum-posts': ForumPost;
    quizzes: Quiz;
    questions: Question;
    'quiz-attempts': QuizAttempt;
    attendance: Attendance;
    grades: Grade;
    announcements: Announcement;
    threads: Thread;
    messages: Message;
    notifications: Notification;
    webinars: Webinar;
    'activity-events': ActivityEvent;
    'site-pages': SitePage;
    roles: Role;
    permissions: Permission;
    'quiz-answers': QuizAnswer;
    media: Media;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    assignments: AssignmentsSelect<false> | AssignmentsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    forums: ForumsSelect<false> | ForumsSelect<true>;
    'forum-posts': ForumPostsSelect<false> | ForumPostsSelect<true>;
    quizzes: QuizzesSelect<false> | QuizzesSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    'quiz-attempts': QuizAttemptsSelect<false> | QuizAttemptsSelect<true>;
    attendance: AttendanceSelect<false> | AttendanceSelect<true>;
    grades: GradesSelect<false> | GradesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    threads: ThreadsSelect<false> | ThreadsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    webinars: WebinarsSelect<false> | WebinarsSelect<true>;
    'activity-events': ActivityEventsSelect<false> | ActivityEventsSelect<true>;
    'site-pages': SitePagesSelect<false> | SitePagesSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    'quiz-answers': QuizAnswersSelect<false> | QuizAnswersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  role: 'SUPER_ADMIN' | 'CO_ADMIN' | 'TEACHER' | 'COMPANY' | 'STUDENT';
  status: 'ACTIVE' | 'INVITED' | 'SUSPENDED' | 'INACTIVE';
  company?: (string | null) | Company;
  permissions?:
    | (
        | 'users.read'
        | 'users.create'
        | 'users.update'
        | 'users.delete'
        | 'courses.read'
        | 'courses.create'
        | 'courses.update'
        | 'courses.delete'
        | 'assignments.create'
        | 'assignments.grade'
        | 'quizzes.create'
        | 'quizzes.grade'
        | 'grades.read'
        | 'grades.update'
        | 'attendance.read'
        | 'attendance.update'
        | 'reports.read'
        | 'audit.read'
        | 'roles.assign'
      )[]
    | null;
  mustChangePassword?: boolean | null;
  profilePhoto?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: string;
  name: string;
  status?: ('ACTIVE' | 'INACTIVE') | null;
  contactName?: string | null;
  contactEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  visibility?: ('PUBLIC' | 'ENROLLED' | 'STAFF' | 'PRIVATE') | null;
  course?: (string | null) | Course;
  uploadedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string;
  title: string;
  slug: string;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (string | null) | Media;
  lifecycleStatus?: ('ACTIVE' | 'ARCHIVED') | null;
  modality?: ('ASYNCHRONOUS' | 'HYBRID' | 'LIVE') | null;
  startAt?: string | null;
  endAt?: string | null;
  estimatedHours?: number | null;
  instructors?: (string | User)[] | null;
  objectives?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  prerequisiteCourse?: (string | null) | Course;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: string;
  student: string | User;
  course: string | Course;
  status?: ('ACTIVE' | 'COMPLETED' | 'DROPPED' | 'EXPIRED') | null;
  progress?: number | null;
  enrolledAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: string;
  course: string | Course;
  title: string;
  weekNumber: number;
  summary?: string | null;
  status?: ('DRAFT' | 'PUBLISHED') | null;
  unlockAt?: string | null;
  prerequisiteModule?: (string | null) | Module;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: string;
  module: string | Module;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  estimatedMinutes?: number | null;
  order: number;
  status?: ('DRAFT' | 'PUBLISHED') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: string;
  course: string | Course;
  module?: (string | null) | Module;
  title: string;
  description?: string | null;
  type: 'DOCUMENT' | 'VIDEO' | 'AUDIO' | 'IMAGE' | 'LINK' | 'INTERACTIVE';
  file?: (string | null) | Media;
  externalUrl?: string | null;
  visibility?: ('ENROLLED' | 'STAFF' | 'PUBLIC') | null;
  allowDownload?: boolean | null;
  status?: ('DRAFT' | 'PUBLISHED') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments".
 */
export interface Assignment {
  id: string;
  course: string | Course;
  module?: (string | null) | Module;
  title: string;
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishAt?: string | null;
  startAt?: string | null;
  dueAt?: string | null;
  maxPoints: number;
  maxAttempts?: number | null;
  allowLate?: boolean | null;
  allowStudentDelete?: boolean | null;
  attachments?: (string | Media)[] | null;
  rubric?:
    | {
        criterion: string;
        points: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: string;
  assignment: string | Assignment;
  student: string | User;
  status?: ('IN_PROGRESS' | 'SUBMITTED' | 'LATE' | 'GRADED' | 'REVISION_REQUIRED' | 'WITHDRAWN') | null;
  text?: string | null;
  files?: (string | Media)[] | null;
  startedAt?: string | null;
  submittedAt?: string | null;
  withdrawnAt?: string | null;
  attempt?: number | null;
  teacherFeedback?: string | null;
  gradedBy?: (string | null) | User;
  gradedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forums".
 */
export interface Forum {
  id: string;
  course: string | Course;
  module?: (string | null) | Module;
  title: string;
  description?: string | null;
  startAt?: string | null;
  endAt?: string | null;
  status?: ('OPEN' | 'CLOSED') | null;
  gradable?: boolean | null;
  maxPoints?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-posts".
 */
export interface ForumPost {
  id: string;
  forum: string | Forum;
  author: string | User;
  parentPost?: (string | null) | ForumPost;
  body: string;
  attachments?: (string | Media)[] | null;
  isPinned?: boolean | null;
  editedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes".
 */
export interface Quiz {
  id: string;
  course: string | Course;
  module?: (string | null) | Module;
  title: string;
  type?: ('QUIZ' | 'EXAM') | null;
  startAt?: string | null;
  endAt?: string | null;
  durationMinutes?: number | null;
  maxAttempts?: number | null;
  shuffleQuestions?: boolean | null;
  shuffleAnswers?: boolean | null;
  showResults?: boolean | null;
  passingScore?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: string;
  quiz: string | Quiz;
  prompt: string;
  type: 'SINGLE' | 'MULTIPLE' | 'TRUE_FALSE' | 'SHORT' | 'LONG';
  points: number;
  options?:
    | {
        label: string;
        isCorrect?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-attempts".
 */
export interface QuizAttempt {
  id: string;
  quiz: string | Quiz;
  student: string | User;
  startedAt: string;
  submittedAt?: string | null;
  score?: number | null;
  status?: ('IN_PROGRESS' | 'SUBMITTED' | 'AUTO_SUBMITTED' | 'GRADED') | null;
  eventCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance".
 */
export interface Attendance {
  id: string;
  course: string | Course;
  student: string | User;
  date: string;
  status: 'PRESENT' | 'ABSENT' | 'LATE' | 'JUSTIFIED';
  source: 'MODULE_ACCESS' | 'REQUIRED_ACTIVITY' | 'CHECK_IN' | 'SESSION' | 'MANUAL';
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grades".
 */
export interface Grade {
  id: string;
  course: string | Course;
  student: string | User;
  activityType: 'ASSIGNMENT' | 'QUIZ' | 'FORUM' | 'MANUAL';
  activityId: string;
  title: string;
  score: number;
  maxScore: number;
  feedback?: string | null;
  gradedBy?: (string | null) | User;
  gradedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  course?: (string | null) | Course;
  title: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  audience?: ('ALL' | 'COURSE' | 'ROLE') | null;
  publishAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "threads".
 */
export interface Thread {
  id: string;
  subject: string;
  type: 'DIRECT' | 'COURSE_GROUP' | 'ADMIN_NOTICE';
  course?: (string | null) | Course;
  participants: (string | User)[];
  lastMessageAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  threadKey: string;
  course?: (string | null) | Course;
  sender: string | User;
  recipients: (string | User)[];
  body: string;
  attachments?: (string | Media)[] | null;
  readBy?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  recipient: string | User;
  type:
    | 'ASSIGNMENT_NEW'
    | 'ASSIGNMENT_DUE'
    | 'GRADE_NEW'
    | 'QUIZ_NEW'
    | 'RESOURCE_NEW'
    | 'FORUM_REPLY'
    | 'MESSAGE_NEW'
    | 'ANNOUNCEMENT'
    | 'COURSE_START'
    | 'COURSE_END';
  title: string;
  body?: string | null;
  href?: string | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars".
 */
export interface Webinar {
  id: string;
  title: string;
  slug: string;
  description?: string | null;
  speaker: string;
  cover?: (string | null) | Media;
  startAt?: string | null;
  endAt?: string | null;
  registrationUrl?: string | null;
  meetingUrl?: string | null;
  recordingUrl?: string | null;
  eventStatus: 'UPCOMING' | 'LIVE' | 'COMPLETED';
  isFree?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-events".
 */
export interface ActivityEvent {
  id: string;
  user: string | User;
  course?: (string | null) | Course;
  quiz?: (string | null) | Quiz;
  attempt?: (string | null) | QuizAttempt;
  event:
    | 'TAB_HIDDEN'
    | 'WINDOW_BLUR'
    | 'FULLSCREEN_EXIT'
    | 'COPY_ATTEMPT'
    | 'PASTE_ATTEMPT'
    | 'EXAM_EXIT'
    | 'NETWORK_RECONNECT'
    | 'RESOURCE_VIEW'
    | 'MODULE_OPEN';
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Constructor visual de contenido público. Disponible únicamente para SUPER_ADMIN.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages".
 */
export interface SitePage {
  id: string;
  title: string;
  slug: 'inicio' | 'cursos' | 'empresa';
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  components?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            showLogo?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'companyInfo';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            courses?: (string | Course)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'courseGrid';
          }
        | {
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            alignment?: ('LEFT' | 'CENTER') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentSection';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  name: string;
  description?: string | null;
  permissions?: (string | Permission)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: string;
  key: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-answers".
 */
export interface QuizAnswer {
  id: string;
  attempt: string | QuizAttempt;
  student: string | User;
  question: string | Question;
  answerText?: string | null;
  selectedOptions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pointsAwarded?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  actor?: (string | null) | User;
  action: string;
  entityType: string;
  entityId?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipHash?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'courses';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: string | Enrollment;
      } | null)
    | ({
        relationTo: 'modules';
        value: string | Module;
      } | null)
    | ({
        relationTo: 'lessons';
        value: string | Lesson;
      } | null)
    | ({
        relationTo: 'resources';
        value: string | Resource;
      } | null)
    | ({
        relationTo: 'assignments';
        value: string | Assignment;
      } | null)
    | ({
        relationTo: 'submissions';
        value: string | Submission;
      } | null)
    | ({
        relationTo: 'forums';
        value: string | Forum;
      } | null)
    | ({
        relationTo: 'forum-posts';
        value: string | ForumPost;
      } | null)
    | ({
        relationTo: 'quizzes';
        value: string | Quiz;
      } | null)
    | ({
        relationTo: 'questions';
        value: string | Question;
      } | null)
    | ({
        relationTo: 'quiz-attempts';
        value: string | QuizAttempt;
      } | null)
    | ({
        relationTo: 'attendance';
        value: string | Attendance;
      } | null)
    | ({
        relationTo: 'grades';
        value: string | Grade;
      } | null)
    | ({
        relationTo: 'announcements';
        value: string | Announcement;
      } | null)
    | ({
        relationTo: 'threads';
        value: string | Thread;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'webinars';
        value: string | Webinar;
      } | null)
    | ({
        relationTo: 'activity-events';
        value: string | ActivityEvent;
      } | null)
    | ({
        relationTo: 'site-pages';
        value: string | SitePage;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null)
    | ({
        relationTo: 'permissions';
        value: string | Permission;
      } | null)
    | ({
        relationTo: 'quiz-answers';
        value: string | QuizAnswer;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  status?: T;
  company?: T;
  permissions?: T;
  mustChangePassword?: T;
  profilePhoto?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  contactName?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  cover?: T;
  lifecycleStatus?: T;
  modality?: T;
  startAt?: T;
  endAt?: T;
  estimatedHours?: T;
  instructors?: T;
  objectives?:
    | T
    | {
        text?: T;
        id?: T;
      };
  prerequisiteCourse?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  student?: T;
  course?: T;
  status?: T;
  progress?: T;
  enrolledAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  course?: T;
  title?: T;
  weekNumber?: T;
  summary?: T;
  status?: T;
  unlockAt?: T;
  prerequisiteModule?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  module?: T;
  title?: T;
  content?: T;
  estimatedMinutes?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  course?: T;
  module?: T;
  title?: T;
  description?: T;
  type?: T;
  file?: T;
  externalUrl?: T;
  visibility?: T;
  allowDownload?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments_select".
 */
export interface AssignmentsSelect<T extends boolean = true> {
  course?: T;
  module?: T;
  title?: T;
  instructions?: T;
  publishAt?: T;
  startAt?: T;
  dueAt?: T;
  maxPoints?: T;
  maxAttempts?: T;
  allowLate?: T;
  allowStudentDelete?: T;
  attachments?: T;
  rubric?:
    | T
    | {
        criterion?: T;
        points?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  assignment?: T;
  student?: T;
  status?: T;
  text?: T;
  files?: T;
  startedAt?: T;
  submittedAt?: T;
  withdrawnAt?: T;
  attempt?: T;
  teacherFeedback?: T;
  gradedBy?: T;
  gradedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forums_select".
 */
export interface ForumsSelect<T extends boolean = true> {
  course?: T;
  module?: T;
  title?: T;
  description?: T;
  startAt?: T;
  endAt?: T;
  status?: T;
  gradable?: T;
  maxPoints?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-posts_select".
 */
export interface ForumPostsSelect<T extends boolean = true> {
  forum?: T;
  author?: T;
  parentPost?: T;
  body?: T;
  attachments?: T;
  isPinned?: T;
  editedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes_select".
 */
export interface QuizzesSelect<T extends boolean = true> {
  course?: T;
  module?: T;
  title?: T;
  type?: T;
  startAt?: T;
  endAt?: T;
  durationMinutes?: T;
  maxAttempts?: T;
  shuffleQuestions?: T;
  shuffleAnswers?: T;
  showResults?: T;
  passingScore?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  quiz?: T;
  prompt?: T;
  type?: T;
  points?: T;
  options?:
    | T
    | {
        label?: T;
        isCorrect?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-attempts_select".
 */
export interface QuizAttemptsSelect<T extends boolean = true> {
  quiz?: T;
  student?: T;
  startedAt?: T;
  submittedAt?: T;
  score?: T;
  status?: T;
  eventCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance_select".
 */
export interface AttendanceSelect<T extends boolean = true> {
  course?: T;
  student?: T;
  date?: T;
  status?: T;
  source?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grades_select".
 */
export interface GradesSelect<T extends boolean = true> {
  course?: T;
  student?: T;
  activityType?: T;
  activityId?: T;
  title?: T;
  score?: T;
  maxScore?: T;
  feedback?: T;
  gradedBy?: T;
  gradedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  course?: T;
  title?: T;
  body?: T;
  audience?: T;
  publishAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "threads_select".
 */
export interface ThreadsSelect<T extends boolean = true> {
  subject?: T;
  type?: T;
  course?: T;
  participants?: T;
  lastMessageAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  threadKey?: T;
  course?: T;
  sender?: T;
  recipients?: T;
  body?: T;
  attachments?: T;
  readBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  body?: T;
  href?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars_select".
 */
export interface WebinarsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  speaker?: T;
  cover?: T;
  startAt?: T;
  endAt?: T;
  registrationUrl?: T;
  meetingUrl?: T;
  recordingUrl?: T;
  eventStatus?: T;
  isFree?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-events_select".
 */
export interface ActivityEventsSelect<T extends boolean = true> {
  user?: T;
  course?: T;
  quiz?: T;
  attempt?: T;
  event?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages_select".
 */
export interface SitePagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  components?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              primaryLabel?: T;
              primaryHref?: T;
              id?: T;
              blockName?: T;
            };
        companyInfo?:
          | T
          | {
              heading?: T;
              body?: T;
              showLogo?: T;
              id?: T;
              blockName?: T;
            };
        courseGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              courses?: T;
              id?: T;
              blockName?: T;
            };
        contentSection?:
          | T
          | {
              heading?: T;
              body?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  permissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  key?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-answers_select".
 */
export interface QuizAnswersSelect<T extends boolean = true> {
  attempt?: T;
  student?: T;
  question?: T;
  answerText?: T;
  selectedOptions?: T;
  pointsAwarded?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  visibility?: T;
  course?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  metadata?: T;
  ipHash?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}