import Link from 'next/link'
import { ArrowUpRight, BookOpen, CheckSquare, ClipboardCheck, GraduationCap } from 'lucide-react'
import { courses, notifications, tasks } from '@/lib/demo-data'
import { CourseCard } from '@/components/course-card'

const kpis=[
  {label:'Cursos activos',value:'2',href:'/campus/cursos',icon:BookOpen},
  {label:'Tareas pendientes',value:'2',href:'/campus/tareas',icon:CheckSquare},
  {label:'Promedio general',value:'91%',href:'/campus/calificaciones',icon:GraduationCap},
  {label:'Asistencia',value:'94%',href:'/campus/asistencia',icon:ClipboardCheck},
]
export default function Page(){return <div className="content"><div className="page-title"><div><span className="section-label">Panel del estudiante</span><h1>Hola, Ana</h1><p className="muted">Consulta tu actividad académica y continúa donde lo dejaste.</p></div></div><div className="kpis">{kpis.map(({label,value,href,icon:Icon})=><Link className="kpi kpi-link" href={href} key={href}><div className="kpi-top"><div className="kpi-icon"><Icon size={18}/></div><ArrowUpRight size={17}/></div><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div></Link>)}</div><div className="dashboard-grid"><section className="panel panel-raised"><div className="panel-heading"><div><span className="section-label">Aprendizaje</span><h3>Cursos en progreso</h3></div><Link href="/campus/cursos" className="text-link">Ver todos <ArrowUpRight size={14}/></Link></div><div className="grid-3" style={{gridTemplateColumns:'repeat(2,1fr)'}}>{courses.slice(0,2).map(c=><CourseCard key={c.slug} course={c} showProgress/>)}</div></section><section className="panel panel-raised"><div className="panel-heading"><div><span className="section-label">Agenda</span><h3>Próximas fechas</h3></div></div><div className="list">{tasks.slice(0,2).map(t=><Link href="/campus/tareas" className="list-item list-link" key={t.title}><div><b>{t.title}</b><div className="muted">{t.course}</div></div><span className="status gold">{t.due}</span></Link>)}</div><div className="panel-heading panel-heading-spaced"><div><span className="section-label">Actividad</span><h3>Notificaciones</h3></div></div><div className="list">{notifications.slice(0,2).map(n=><Link href="/campus/notificaciones" className="list-item list-link" key={n.title}><div><b>{n.title}</b><div className="muted">{n.body}</div></div></Link>)}</div></section></div></div>}
